"use client";

import { type DragEvent, type KeyboardEvent, type PointerEvent, useEffect, useState } from "react";
import { reorderSiblings } from "@/lib/content-taxonomy-order";

type Kind = "destination" | "topic" | "system";
type Taxon = { id: string; label: string; kind: Kind; parent_id: string | null; aliases: string[]; show_in_nav: boolean; sort_order: number; href: string | null };
type FormState = { label: string; kind: "destination" | "topic"; parentId: string; aliases: string; showInNav: boolean };
type Dragging = { id: string; parentId: string | null } | null;
const emptyForm: FormState = { label: "", kind: "destination", parentId: "", aliases: "", showInNav: true };

export default function ContentNavigationManager() {
  const [taxa, setTaxa] = useState<Taxon[]>([]); const [form, setForm] = useState<FormState>(emptyForm); const [editingId, setEditingId] = useState<string | null>(null); const [message, setMessage] = useState("載入中…"); const [saving, setSaving] = useState(false);
  const [dragging, setDragging] = useState<Dragging>(null); const [dragOverId, setDragOverId] = useState<string | null>(null);

  function load() { fetch("/api/content-taxa").then(async (response) => ({ response, data: await response.json() })).then(({ response, data }) => { if (response.ok) { setTaxa(data.taxa); setMessage(""); } else setMessage(data.error || "無法載入分類，請先執行最新 migration。"); }).catch(() => setMessage("無法載入分類。")); }
  useEffect(() => { load(); }, []);
  const roots = taxa.filter((item) => !item.parent_id).sort((a, b) => a.sort_order - b.sort_order);
  const parentOptions = roots.filter((item) => item.kind !== "system");

  function resetForm() { setEditingId(null); setForm(emptyForm); }
  function edit(item: Taxon) { if (item.kind === "system") return; setEditingId(item.id); setForm({ label: item.label, kind: item.kind, parentId: item.parent_id ?? "", aliases: item.aliases.filter((alias) => alias !== item.label).join(", "), showInNav: item.show_in_nav }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function saveForm() {
    setSaving(true); const response = await fetch("/api/content-taxa", { method: editingId ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...(editingId ? { id: editingId } : {}), label: form.label, kind: form.kind, parentId: form.parentId || null, aliases: form.aliases, showInNav: form.showInNav }) }); const data = await response.json(); setSaving(false);
    if (!response.ok) return setMessage(data.error || "儲存失敗。"); setMessage(editingId ? "分類已更新。" : "分類已建立。"); resetForm(); load();
  }
  async function setVisibility(item: Taxon, visible: boolean) { setTaxa((current) => current.map((value) => value.id === item.id ? { ...value, show_in_nav: visible } : value)); const response = await fetch("/api/content-taxa", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: item.id, showInNav: visible }) }); if (!response.ok) { setMessage("顯示設定更新失敗。"); load(); } }
  async function remove(item: Taxon) { if (!window.confirm(`確定刪除「${item.label}」嗎？子分類與文章標記也會一起移除。`)) return; const response = await fetch(`/api/content-taxa?id=${encodeURIComponent(item.id)}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) setMessage(data.error || "刪除失敗。"); else { setMessage("分類已刪除。"); load(); } }

  function siblingsOf(item: Taxon) { return taxa.filter((value) => value.parent_id === item.parent_id).sort((a, b) => a.sort_order - b.sort_order); }
  async function reorder(sourceId: string, targetId: string) {
    const source = taxa.find((item) => item.id === sourceId); const target = taxa.find((item) => item.id === targetId); if (!source || !target || source.id === target.id || source.parent_id !== target.parent_id) return endDrag();
    const reordered = reorderSiblings(taxa, sourceId, targetId); if (!reordered) return endDrag();
    const order = new Map(reordered.map((item) => [item.id, item.sort_order])); setTaxa((current) => current.map((item) => order.has(item.id) ? { ...item, sort_order: order.get(item.id)! } : item)); endDrag();
    const response = await fetch("/api/content-taxa", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ parentId: source.parent_id, ids: reordered.map((item) => item.id) }) }); if (!response.ok) { setMessage("排序儲存失敗，已重新載入。"); load(); } else setMessage("排序已自動儲存。");
  }
  function startDrag(event: DragEvent, item: Taxon) { event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("text/plain", item.id); setDragging({ id: item.id, parentId: item.parent_id }); }
  function dragOver(event: DragEvent, item: Taxon) { if (dragging?.parentId === item.parent_id) { event.preventDefault(); event.dataTransfer.dropEffect = "move"; setDragOverId(item.id); } }
  function drop(event: DragEvent, item: Taxon) { event.preventDefault(); if (dragging) void reorder(dragging.id, item.id); }
  function pointerDown(event: PointerEvent, item: Taxon) { if (event.pointerType !== "touch") return; event.currentTarget.setPointerCapture(event.pointerId); setDragging({ id: item.id, parentId: item.parent_id }); setDragOverId(item.id); }
  function pointerMove(event: PointerEvent) { if (event.pointerType !== "touch" || !dragging) return; const element = document.elementFromPoint(event.clientX, event.clientY)?.closest<HTMLElement>("[data-taxon-id]"); const target = element ? taxa.find((item) => item.id === element.dataset.taxonId) : null; if (target?.parent_id === dragging.parentId) setDragOverId(target.id); }
  function pointerUp(event: PointerEvent) { if (event.pointerType !== "touch" || !dragging) return; if (dragOverId) void reorder(dragging.id, dragOverId); else endDrag(); }
  function keyMove(event: KeyboardEvent, item: Taxon) { if (event.key !== "ArrowUp" && event.key !== "ArrowDown") return; event.preventDefault(); const siblings = siblingsOf(item); const index = siblings.findIndex((value) => value.id === item.id); const target = siblings[index + (event.key === "ArrowUp" ? -1 : 1)]; if (target) void reorder(item.id, target.id); }
  function endDrag() { setDragging(null); setDragOverId(null); }
  const handle = (item: Taxon) => <button type="button" draggable onDragStart={(event) => startDrag(event, item)} onDragEnd={endDrag} onPointerDown={(event) => pointerDown(event, item)} onPointerMove={pointerMove} onPointerUp={pointerUp} onKeyDown={(event) => keyMove(event, item)} title="拖曳排序；鍵盤可用上下方向鍵" aria-label={`調整 ${item.label} 的順序`} className="touch-none cursor-grab select-none rounded-lg px-2 py-1 text-lg leading-none text-[#819188] hover:bg-white hover:text-[#c1664b] active:cursor-grabbing">⠿</button>;
  const rowClass = (item: Taxon, child = false) => `${child ? "mt-2 py-2 pl-3 pr-2 text-sm" : "p-4"} rounded-2xl border-2 transition ${dragOverId === item.id && dragging?.id !== item.id ? "border-[#c1664b] bg-[#fff7f2]" : dragging?.id === item.id ? "border-transparent bg-[#eef2ee] opacity-50 shadow-lg" : child ? "border-transparent border-l-[#d3dfd8]" : "border-transparent bg-[#f5f7f3]"}`;

  return <main className="min-h-screen px-6 py-8"><section className="mx-auto max-w-5xl py-4"><p className="text-sm tracking-[0.2em] text-[#c1664b]">CONTENT NAVIGATION</p><h1 className="mt-3 text-4xl font-semibold text-[#31413d]">導覽與分類管理</h1><p className="mt-4 text-[#718078]">目的地、主題與系統頁面共用同一份 Navbar 順序。拖曳六點把手即可排序。</p>{message && <p className="mt-5 rounded-2xl bg-white p-4 text-sm text-[#718078]">{message}</p>}
    <section className="mt-8 rounded-3xl bg-white p-6 shadow-sm"><h2 className="font-semibold">{editingId ? "編輯分類" : "建立分類"}</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><input value={form.label} onChange={(event) => setForm({ ...form, label: event.target.value })} placeholder="例如：美洲、學習成長、馬來西亞" className="rounded-xl border px-3 py-2" /><select value={form.kind} onChange={(event) => setForm({ ...form, kind: event.target.value as FormState["kind"], parentId: "" })} className="rounded-xl border px-3 py-2"><option value="destination">目的地</option><option value="topic">主題分類</option></select><select value={form.parentId} onChange={(event) => setForm({ ...form, parentId: event.target.value })} className="rounded-xl border px-3 py-2"><option value="">無上層（Navbar 主項目）</option>{parentOptions.filter((item) => item.id !== editingId).map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><input value={form.aliases} onChange={(event) => setForm({ ...form, aliases: event.target.value })} placeholder="辨識別名（可選），用逗號分隔" className="rounded-xl border px-3 py-2" /></div><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={form.showInNav} onChange={(event) => setForm({ ...form, showInNav: event.target.checked })} />顯示在 Navbar</label><div className="mt-5 flex gap-3"><button type="button" onClick={() => void saveForm()} disabled={saving} className="rounded-full bg-[#c1664b] px-5 py-3 text-sm text-white disabled:opacity-50">{editingId ? "儲存修改" : "建立分類"}</button>{editingId && <button type="button" onClick={resetForm} className="rounded-full border px-5 py-3 text-sm">取消</button>}</div></section>
    <section className="mt-6 rounded-3xl bg-white p-6 shadow-sm"><h2 className="font-semibold">Navbar 與分類順序</h2><div className="mt-4 space-y-3">{roots.map((root) => <div key={root.id} data-taxon-id={root.id} onDragOver={(event) => dragOver(event, root)} onDrop={(event) => drop(event, root)} className={rowClass(root)}><div className="flex flex-wrap items-center gap-2">{handle(root)}<strong className="mr-auto">{root.label}</strong><span className="rounded-full bg-white px-2 py-1 text-xs text-[#7a8b83]">{root.kind === "system" ? "系統頁面" : root.kind === "destination" ? "目的地" : "主題"}</span><label className="text-sm"><input type="checkbox" checked={root.show_in_nav} onChange={(event) => void setVisibility(root, event.target.checked)} /> 顯示</label>{root.kind !== "system" && <><button onClick={() => edit(root)} className="text-sm text-[#557166]">編輯</button><button onClick={() => void remove(root)} className="text-sm text-[#9a4d42]">刪除</button></>}</div>{taxa.filter((item) => item.parent_id === root.id).sort((a, b) => a.sort_order - b.sort_order).map((child) => <div key={child.id} data-taxon-id={child.id} onDragOver={(event) => dragOver(event, child)} onDrop={(event) => drop(event, child)} className={rowClass(child, true)}><div className="flex items-center gap-2">{handle(child)}<span className="mr-auto">{child.label}</span><label><input type="checkbox" checked={child.show_in_nav} onChange={(event) => void setVisibility(child, event.target.checked)} /> 顯示</label><button onClick={() => edit(child)} className="text-[#557166]">編輯</button><button onClick={() => void remove(child)} className="text-[#9a4d42]">刪除</button></div></div>)}</div>)}</div></section>
  </section></main>;
}
