"use client";

import { useMemo, useState } from "react";
import Link from "next/link";

type ImportedPost = { importId: string; date: string | null; title: string; text: string; mediaLinks: string[] };

export default function FacebookImportPreview({ posts }: { posts: ImportedPost[] }) {
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<string[]>([]);
  const filtered = useMemo(() => posts.filter((post) => `${post.title} ${post.text}`.toLowerCase().includes(query.toLowerCase())), [posts, query]);
  const allVisibleSelected = filtered.length > 0 && filtered.every((post) => selected.includes(post.importId));
  function toggle(id: string) { setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); }
  function toggleVisible() { setSelected((current) => allVisibleSelected ? current.filter((id) => !filtered.some((post) => post.importId === id)) : [...new Set([...current, ...filtered.map((post) => post.importId)])]); }

  return <main className="min-h-screen bg-[#f5f7f3] px-6 py-8"><nav className="mx-auto flex max-w-6xl justify-between"><Link href="/" className="text-lg font-semibold tracking-[0.16em] text-[#31413d]">天天寶寶旅行趣</Link><Link href="/admin" className="text-sm text-[#c1664b]">← 回作者後台</Link></nav><section className="mx-auto max-w-6xl py-12"><p className="text-sm tracking-[0.2em] text-[#c1664b]">FACEBOOK ARCHIVE</p><h1 className="mt-3 text-4xl font-semibold text-[#31413d]">匯入預覽</h1><p className="mt-4 max-w-2xl leading-7 text-[#718078]">先挑選想整理的文章，確認文字與媒體關聯後，再進行分類與匯入。原始 Facebook 資料目前保持不變。</p><div className="mt-8 flex flex-col justify-between gap-4 rounded-3xl bg-white p-5 shadow-sm sm:flex-row sm:items-center"><div className="flex flex-wrap gap-5 text-sm text-[#64776d]"><span>共 {posts.length} 篇</span><span>目前顯示 {filtered.length} 篇</span><span>已選 {selected.length} 篇</span></div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜尋貼文內容" className="rounded-full border border-[#d3dfd8] px-4 py-2 text-sm outline-none focus:border-[#c1664b]" /></div><div className="mt-5 flex items-center justify-between"><label className="flex items-center gap-2 text-sm text-[#64776d]"><input type="checkbox" checked={allVisibleSelected} onChange={toggleVisible} className="accent-[#c1664b]" />選取目前顯示的文章</label><button disabled={!selected.length} className="rounded-full bg-[#c1664b] px-5 py-2 text-sm text-white disabled:opacity-40">建立匯入草稿</button></div><div className="mt-5 space-y-4">{filtered.map((post) => <article key={post.importId} className={`rounded-3xl bg-white p-5 shadow-sm transition ${selected.includes(post.importId) ? "ring-2 ring-[#c1664b]" : ""}`}><div className="flex gap-4"><input type="checkbox" checked={selected.includes(post.importId)} onChange={() => toggle(post.importId)} className="mt-1 h-4 w-4 accent-[#c1664b]" /><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-2"><p className="text-xs tracking-[0.12em] text-[#c1664b]">{post.date ? new Date(post.date).toLocaleDateString("zh-TW") : "無日期"} · {post.importId}</p><span className="text-xs text-[#7a8b83]">{post.mediaLinks.length} 個媒體</span></div><h2 className="mt-2 font-semibold text-[#31413d]">{post.title || "未命名貼文"}</h2><p className="mt-3 max-h-28 overflow-hidden whitespace-pre-wrap text-sm leading-6 text-[#718078]">{post.text || "（此貼文沒有可解析的文字，可能是連結或單純媒體貼文。）"}</p></div></div></article>)}{filtered.length === 0 && <p className="rounded-3xl bg-white p-10 text-center text-[#7a8b83]">找不到符合的貼文。</p>}</div></section></main>;
}
