"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { stories as fallback } from "@/lib/stories";

type Story = { slug: string; title: string; body: string; category: string; country: string | null; city: string | null; published_at: string | null };
const categories = ["全部", "國外旅行", "台灣旅行", "日常生活"];
export default function Home() {
  const [stories, setStories] = useState<Story[]>([]); const [query, setQuery] = useState(""); const [category, setCategory] = useState("全部");
  useEffect(() => { fetch("/api/published-stories").then((r) => r.json()).then((data) => setStories(data.stories ?? [])).catch(() => setStories([])); }, []);
  const visible = useMemo(() => (stories.length ? stories : fallback.map((s) => ({ slug: s.slug, title: s.title, body: `${s.excerpt}\n\n${s.paragraphs.join("\n\n")}`, category: s.category, country: s.country, city: s.city, published_at: s.date }))).filter((s) => (category === "全部" || s.category === category) && `${s.title} ${s.body} ${s.country ?? ""} ${s.city ?? ""}`.toLowerCase().includes(query.toLowerCase())), [stories, query, category]);
  return <main className="min-h-screen bg-[#fdfcf8] text-[#31413d]"><nav className="mx-auto flex max-w-6xl justify-between px-6 py-7"><Link href="/" className="text-lg font-semibold tracking-[0.16em]">天天寶寶旅行趣</Link><Link href="/admin" className="text-sm text-[#c1664b]">作者後台</Link></nav><header className="mx-auto max-w-6xl px-6 pb-16 pt-16"><p className="text-sm tracking-[0.25em] text-[#c1664b]">OUR TRAVEL ARCHIVE</p><h1 className="mt-4 max-w-2xl text-5xl font-semibold leading-tight sm:text-7xl">把一起走過的路，寫成故事。</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#687a73]">記錄我們的旅行、生活，以及那些值得回頭看的日子。</p></header><section id="stories" className="mx-auto max-w-6xl px-6 pb-24"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex flex-wrap gap-2">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`rounded-full px-4 py-2 text-sm ${category === item ? "bg-[#c1664b] text-white" : "bg-[#eaf0eb] text-[#587067]"}`}>{item}</button>)}</div><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜尋國家、城市或文章" className="rounded-full border border-[#d3dfd8] px-4 py-2 text-sm outline-none" /></div><div className="mt-10 grid gap-8 md:grid-cols-3">{visible.map((story) => <article key={story.slug} className="rounded-3xl bg-white p-6 shadow-sm"><p className="text-xs text-[#c1664b]">{story.category} · {story.country ?? ""}</p><h2 className="mt-3 text-2xl font-semibold"><Link href={`/stories/${story.slug}`} className="hover:text-[#c1664b]">{story.title}</Link></h2><p className="mt-3 line-clamp-4 whitespace-pre-line text-sm leading-7 text-[#718078]">{story.body}</p></article>)}</div>{visible.length === 0 && <p className="mt-10 text-center text-[#718078]">目前沒有符合的文章。</p>}</section></main>;
}
