"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { stories } from "@/lib/stories";

const categories = ["全部", "國外旅行", "台灣旅行", "日常生活"] as const;

export default function Home() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState<(typeof categories)[number]>("全部");
  const results = useMemo(() => stories.filter((story) => {
    const matchesCategory = category === "全部" || story.category === category;
    const haystack = `${story.title} ${story.excerpt} ${story.country} ${story.city} ${story.place}`;
    return matchesCategory && haystack.toLowerCase().includes(query.toLowerCase());
  }), [category, query]);

  return <main className="min-h-screen overflow-hidden">
    <nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-7 lg:px-10"><Link href="#top" className="text-lg font-semibold tracking-[0.16em] text-[#31413d]">天天寶寶旅行趣</Link><div className="hidden items-center gap-8 text-sm text-[#61716c] sm:flex"><Link href="#stories">最新故事</Link><Link href="#categories">探索分類</Link><Link href="#about">關於我們</Link></div><Link href="#stories" className="rounded-full border border-[#cad8d0] px-4 py-2 text-sm text-[#4c655d]">搜尋故事</Link></nav>
    <section id="top" className="mx-auto grid max-w-6xl items-center gap-12 px-6 pb-20 pt-10 lg:grid-cols-[1fr_0.9fr] lg:px-10 lg:pb-28 lg:pt-20"><div><p className="mb-6 text-sm font-medium tracking-[0.25em] text-[#c1664b]">OUR LITTLE TRAVEL ARCHIVE</p><h1 className="max-w-xl text-5xl font-semibold leading-[1.12] tracking-[-0.04em] text-[#31413d] sm:text-7xl">把走過的地方，<span className="text-[#c1664b]">好好記下來。</span></h1><p className="mt-7 max-w-lg text-lg leading-8 text-[#687a73]">這裡是天天寶寶的旅行故事，也是一個把風景、食物和我們一起走過的日子收藏起來的地方。</p><a href="#stories" className="mt-9 inline-block rounded-full bg-[#c1664b] px-6 py-3 text-sm font-medium text-white shadow-lg shadow-[#c1664b]/20">開始閱讀故事</a></div><div className="relative mx-auto w-full max-w-md"><div className="relative aspect-[4/5] rotate-2 overflow-hidden rounded-[2rem] bg-gradient-to-br from-[#7ba3a1] via-[#d9c4a6] to-[#d77b5c] p-4 shadow-2xl"><div className="flex h-full flex-col justify-between rounded-[1.5rem] border border-white/50 bg-white/10 p-6 text-white"><div className="flex justify-between text-xs tracking-[0.2em]"><span>TRAVEL NOTES</span><span>2024—25</span></div><div><p className="text-6xl">🌍</p><p className="mt-5 text-3xl font-semibold leading-tight">半年環遊世界<br />的那些日子</p><p className="mt-3 text-sm text-white/80">everywhere we went, together</p></div></div></div></div></section>
    <section id="categories" className="bg-[#eaf0eb]/70 px-6 py-20 lg:px-10"><div className="mx-auto max-w-6xl"><p className="text-sm tracking-[0.2em] text-[#c1664b]">EXPLORE</p><h2 className="mt-2 text-3xl font-semibold text-[#31413d] sm:text-4xl">從哪一段故事開始？</h2><div className="mt-10 flex flex-wrap gap-3">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`rounded-full px-5 py-3 text-sm transition ${category === item ? "bg-[#c1664b] text-white" : "bg-white text-[#587067] hover:text-[#c1664b]"}`}>{item}</button>)}</div></div></section>
    <section id="stories" className="mx-auto max-w-6xl px-6 py-20 lg:px-10 lg:py-28"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm tracking-[0.2em] text-[#c1664b]">LATEST STORIES</p><h2 className="mt-2 text-3xl font-semibold text-[#31413d] sm:text-4xl">最近寫下的風景</h2></div><label className="flex items-center rounded-full border border-[#d3dfd8] bg-white px-4 py-2 text-sm text-[#718078]"><span className="mr-2">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜尋國家、城市或故事" className="w-52 bg-transparent outline-none placeholder:text-[#a4b0aa]" /></label></div><div className="mt-10 grid gap-8 md:grid-cols-3">{results.map((story) => <article key={story.slug} className="group"><Link href={`/stories/${story.slug}`}><div className={`relative aspect-[4/3] overflow-hidden rounded-3xl bg-gradient-to-br ${story.tone} p-5 shadow-sm`}><div className="flex h-full items-end rounded-2xl border border-white/30 bg-black/5 p-5"><span className="text-sm font-medium text-white/90">{story.place}</span></div><span className="absolute right-5 top-5 rounded-full bg-white/80 px-3 py-1 text-xs text-[#53645d]">{story.category}</span></div><p className="mt-5 text-xs tracking-[0.12em] text-[#c1664b]">{story.date} ・ {story.place}</p><h3 className="mt-2 text-xl font-semibold leading-snug text-[#31413d] transition group-hover:text-[#c1664b]">{story.title}</h3><p className="mt-2 text-sm leading-6 text-[#78877f]">{story.excerpt}</p></Link></article>)}</div>{results.length === 0 && <p className="mt-10 rounded-2xl bg-[#f4f6f2] p-8 text-center text-[#718078]">找不到相關故事，試試其他國家或城市。</p>}</section>
    <section id="about" className="bg-[#31413d] px-6 py-16 text-white lg:px-10"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-8 sm:flex-row sm:items-end"><div><p className="text-sm tracking-[0.2em] text-[#f0c28f]">ABOUT US</p><h2 className="mt-3 text-3xl font-semibold">嗨，我們是天天寶寶。</h2><p className="mt-4 max-w-md leading-7 text-white/65">喜歡一起出發，也喜歡回家後慢慢整理那些照片和故事。謝謝你來到這裡。</p></div><p className="text-sm text-white/45">一個屬於我們，也分享給你的旅行檔案。</p></div></section>
  </main>;
}
