"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { type FormEvent, useEffect, useState } from "react";
import type { PublicNavbarItem } from "@/lib/navbar-types";
import { getSupabaseBrowserClient, isCurrentUserAuthor } from "@/lib/supabase-browser";

export default function PublicNavbar() {
  const pathname = usePathname(); const router = useRouter();
  const [items, setItems] = useState<PublicNavbarItem[]>([]); const [query, setQuery] = useState(""); const [mobileOpen, setMobileOpen] = useState(false); const [isAuthor, setIsAuthor] = useState(false);
  useEffect(() => { fetch("/api/navigation").then((response) => response.ok ? response.json() : { items: [] }).then((data) => Array.isArray(data.items) && setItems(data.items)).catch(() => undefined); isCurrentUserAuthor().then(setIsAuthor).catch(() => undefined); }, []);
  function close() { setMobileOpen(false); }
  function search(event: FormEvent) { event.preventDefault(); const value = query.trim(); router.push(value ? `/?q=${encodeURIComponent(value)}#stories` : "/#stories"); close(); }
  async function authorArea() { if (isAuthor) return router.push("/admin"); const supabase = getSupabaseBrowserClient(); if (!supabase) return router.push("/admin"); const { error } = await supabase.auth.signInWithOAuth({ provider: "google", options: { redirectTo: `${window.location.origin}/auth/callback` } }); if (error) router.push("/admin"); }
  const searchForm = (mobile = false) => <form onSubmit={search} className={mobile ? "flex gap-2" : "ml-3 flex items-center"}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜尋標題" aria-label="搜尋文章標題" className={`${mobile ? "min-w-0 flex-1" : "w-32 lg:w-40"} rounded-full border border-[#d3dfd8] bg-white px-3 py-2 text-sm outline-none`} /><button className="rounded-full bg-[#c1664b] px-3 py-2 text-sm text-white">搜尋</button></form>;
  const target = (item: PublicNavbarItem) => item.type === "destination" ? `/regions/${item.region.slug}` : item.href;
  const children = (item: PublicNavbarItem) => item.type === "destination" ? item.region.countries.map((country) => ({ id: country.slug, label: country.label, href: `/regions/${item.region.slug}/${country.slug}` })) : item.type === "group" ? item.children : [];
  const desktopItem = (item: PublicNavbarItem) => { const href = target(item); const subitems = children(item); if (!subitems.length) return <Link key={item.id} href={href} className={`px-2 text-sm lg:px-4 ${pathname === href ? "text-[#c1664b]" : "text-[#52655d] hover:text-[#c1664b]"}`}>{item.label}</Link>; return <div key={item.id} className="group relative flex h-full items-center"><Link href={href} className={`flex h-full items-center gap-1 px-2 text-sm lg:px-4 ${pathname.startsWith(href) ? "text-[#c1664b]" : "text-[#52655d] hover:text-[#c1664b]"}`}>{item.label}<span className="text-xs">⌄</span></Link><div className="invisible absolute left-1/2 top-full w-64 -translate-x-1/2 translate-y-2 rounded-2xl border border-[#e1e8e2] bg-white p-3 opacity-0 shadow-xl transition group-hover:visible group-hover:translate-y-0 group-hover:opacity-100 group-focus-within:visible group-focus-within:opacity-100"><Link href={href} className="block rounded-xl px-3 py-2 text-sm font-medium text-[#31413d] hover:bg-[#f3f6f3]">查看所有{item.label}文章</Link><div className="my-2 border-t border-[#edf1ed]" />{subitems.map((child) => <Link key={child.id} href={child.href} className="block rounded-xl px-3 py-2 text-sm text-[#64776d] hover:bg-[#f3f6f3] hover:text-[#c1664b]">{child.label}</Link>)}</div></div>; };
  return <header className="sticky top-0 z-40 border-b border-[#e4eae5] bg-[#fdfcf8]/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:px-6"><Link href="/" onClick={close} className="text-base font-semibold tracking-[0.14em] text-[#31413d] sm:text-lg">天天寶寶旅行趣</Link><nav className="hidden h-full items-center md:flex" aria-label="主要導覽">{items.map(desktopItem)}{searchForm()}<button type="button" onClick={() => void authorArea()} className="ml-3 rounded-full border border-[#c1664b] px-3 py-2 text-sm text-[#c1664b]">{isAuthor ? "進入後台" : "管理者登入"}</button></nav><button type="button" onClick={() => setMobileOpen((value) => !value)} className="rounded-full border px-4 py-2 text-sm md:hidden">{mobileOpen ? "關閉" : "選單"}</button></div>{mobileOpen && <nav className="border-t bg-white px-5 py-4 md:hidden">{searchForm(true)}<div className="mt-3">{items.map((item) => <div key={item.id} className="border-b py-1"><Link href={target(item)} onClick={close} className="block py-3 font-medium">{item.label}</Link>{children(item).map((child) => <Link key={child.id} href={child.href} onClick={close} className="block py-2 pl-4 text-sm text-[#64776d]">{child.label}</Link>)}</div>)}</div><button type="button" onClick={() => void authorArea()} className="mt-4 w-full rounded-xl border border-[#c1664b] px-4 py-3 text-sm text-[#c1664b]">{isAuthor ? "進入後台" : "管理者登入"}</button></nav>}</header>;
}
