"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { type FormEvent, useEffect, useState } from "react";
import { emptyDestinationNavigation, type DestinationNavigation, type RegionSlug } from "@/lib/destination";

type NavigationRegion = DestinationNavigation[number];

export default function PublicNavbar() {
  const pathname = usePathname(); const router = useRouter();
  const [navigation, setNavigation] = useState<NavigationRegion[]>(emptyDestinationNavigation());
  const [searchQuery, setSearchQuery] = useState(""); const [mobileOpen, setMobileOpen] = useState(false); const [mobileRegion, setMobileRegion] = useState<RegionSlug | null>(null);
  useEffect(() => { fetch("/api/navigation").then((response) => response.ok ? response.json() : { navigation: [] }).then((data) => data.navigation?.length && setNavigation(data.navigation)).catch(() => undefined); }, []);
  function closeMobile() { setMobileOpen(false); setMobileRegion(null); }
  function searchTitles(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const query = searchQuery.trim(); router.push(query ? `/?q=${encodeURIComponent(query)}#stories` : "/#stories"); window.dispatchEvent(new CustomEvent("title-search", { detail: query })); closeMobile(); }
  const searchForm = (mobile = false) => <form onSubmit={searchTitles} role="search" className={mobile ? "mt-3 flex gap-2" : "ml-3 flex items-center"}><input value={searchQuery} onChange={(event) => setSearchQuery(event.target.value)} placeholder="搜尋標題" aria-label="搜尋文章標題" className={`${mobile ? "min-w-0 flex-1" : "w-32 lg:w-40"} rounded-full border border-[#d3dfd8] bg-white px-3 py-2 text-sm text-[#31413d] outline-none focus:border-[#c1664b]`} /><button type="submit" className="rounded-full bg-[#c1664b] px-3 py-2 text-sm text-white">搜尋</button></form>;
  const countryHref = (region: NavigationRegion, country: { slug: string }) => `/regions/${region.slug}/${country.slug}`;
  const desktopRegion = (region: NavigationRegion) => <div key={region.slug} className="group relative flex h-full items-center"><Link href={`/regions/${region.slug}`} className={`flex h-full items-center gap-1 px-2 text-sm transition lg:px-4 ${pathname.startsWith(`/regions/${region.slug}`) ? "text-[#c1664b]" : "text-[#52655d] hover:text-[#c1664b]"}`}>{region.label}<span aria-hidden="true" className="text-xs">⌄</span></Link><div className="invisible absolute left-1/2 top-full w-64 -translate-x-1/2 translate-y-2 rounded-2xl border border-[#e1e8e2] bg-white p-3 opacity-0 shadow-xl transition group-hover:visible group-hover:translate-y-0 group-hover:opacity-100 group-focus-within:visible group-focus-within:translate-y-0 group-focus-within:opacity-100">{pathname === `/regions/${region.slug}` ? <span aria-current="page" className="flex items-center justify-between rounded-xl bg-[#f7eee9] px-3 py-2 text-sm font-medium text-[#c1664b]">查看所有{region.label}文章<span className="text-xs">目前瀏覽</span></span> : <Link href={`/regions/${region.slug}`} className="block rounded-xl px-3 py-2 text-sm font-medium text-[#31413d] hover:bg-[#f3f6f3]">查看所有{region.label}文章</Link>}{region.countries.length > 0 && <><div className="my-2 border-t border-[#edf1ed]" />{region.countries.map((country) => pathname === countryHref(region, country) ? <span key={country.slug} aria-current="page" className="flex items-center justify-between rounded-xl bg-[#f7eee9] px-3 py-2 text-sm font-medium text-[#c1664b]">{country.label}<span className="text-xs">目前瀏覽</span></span> : <Link key={country.slug} href={countryHref(region, country)} className="block rounded-xl px-3 py-2 text-sm text-[#64776d] hover:bg-[#f3f6f3] hover:text-[#c1664b]">{country.label}</Link>)}</>}{region.slug !== "taiwan" && !region.countries.length && <><div className="my-2 border-t border-[#edf1ed]" /><p className="px-3 py-2 text-xs text-[#9aa8a0]">文章國家整理中</p></>}</div></div>;
  return <header className="sticky top-0 z-40 border-b border-[#e4eae5] bg-[#fdfcf8]/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:px-6"><Link href="/" onClick={closeMobile} className="text-base font-semibold tracking-[0.14em] text-[#31413d] sm:text-lg">天天寶寶旅行趣</Link><nav aria-label="主要導覽" className="hidden h-full items-center md:flex">{navigation.map(desktopRegion)}<Link href="/categories/daily-life" className={`px-2 text-sm lg:px-4 ${pathname === "/categories/daily-life" ? "text-[#c1664b]" : "text-[#52655d] hover:text-[#c1664b]"}`}>日常生活</Link><Link href="/videos" className={`px-2 text-sm lg:px-4 ${pathname === "/videos" ? "text-[#c1664b]" : "text-[#52655d] hover:text-[#c1664b]"}`}>影片專區</Link>{searchForm()}</nav><button type="button" onClick={() => setMobileOpen((open) => !open)} aria-expanded={mobileOpen} aria-controls="mobile-public-navigation" className="rounded-full border border-[#d3dfd8] px-4 py-2 text-sm text-[#557166] md:hidden">{mobileOpen ? "關閉" : "選單"}</button></div>{mobileOpen && <nav id="mobile-public-navigation" aria-label="手機主要導覽" className="max-h-[calc(100vh-4rem)] overflow-y-auto border-t border-[#e4eae5] bg-white px-5 py-4 md:hidden">{searchForm(true)}<div className="mt-3">{navigation.map((region) => <div key={region.slug} className="border-b border-[#edf1ed] py-1"><div className="flex items-center justify-between"><Link href={`/regions/${region.slug}`} onClick={closeMobile} className="flex-1 py-3 font-medium text-[#31413d]">{region.label}</Link>{region.countries.length > 0 && <button type="button" onClick={() => setMobileRegion((current) => current === region.slug ? null : region.slug)} aria-expanded={mobileRegion === region.slug} className="px-4 py-3 text-[#7a8b83]">{mobileRegion === region.slug ? "−" : "+"}</button>}</div>{mobileRegion === region.slug && <div className="pb-3 pl-4">{region.countries.map((country) => pathname === countryHref(region, country) ? <span key={country.slug} aria-current="page" className="block py-2 text-sm font-medium text-[#c1664b]">{country.label}（目前瀏覽）</span> : <Link key={country.slug} href={countryHref(region, country)} onClick={closeMobile} className="block py-2 text-sm text-[#64776d]">{country.label}</Link>)}</div>}</div>)}<Link href="/categories/daily-life" onClick={closeMobile} className="block border-b border-[#edf1ed] py-4 font-medium text-[#31413d]">日常生活</Link><Link href="/videos" onClick={closeMobile} className="block py-4 font-medium text-[#31413d]">影片專區</Link></div></nav>}</header>;
}
