"use client";

import { useState } from "react";

export default function ContentSafety() {
  const [trashOpen, setTrashOpen] = useState(false);
  const [notifications, setNotifications] = useState(true);
  return <div className="space-y-4"><section className="rounded-3xl bg-[#31413d] p-6 text-white"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-[#f0c28f]">BACKUP</p><h2 className="mt-2 text-xl font-semibold">回憶有被好好保存</h2><p className="mt-2 text-sm leading-6 text-white/65">文章、照片與影片會定期備份。完成資料庫設定後，這裡會顯示最新備份時間。</p></div><span className="rounded-full bg-white/10 px-3 py-1 text-xs text-[#d8e8dc]">展示狀態</span></div><div className="mt-5 flex items-center justify-between border-t border-white/10 pt-4 text-sm"><span className="text-white/60">最近備份</span><span>尚未連接 Supabase</span></div></section><section className="rounded-3xl bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-medium text-[#52655d]">垃圾桶</p><p className="mt-1 text-sm text-[#7a8b83]">刪除的內容保留 30 天，可隨時復原。</p></div><button onClick={() => setTrashOpen(!trashOpen)} className="rounded-full border border-[#d3dfd8] px-4 py-2 text-sm text-[#557166]">{trashOpen ? "收起" : "查看垃圾桶"}</button></div>{trashOpen && <div className="mt-5 rounded-2xl bg-[#f5f7f3] p-4 text-sm text-[#9aa8a0]">目前沒有可復原的內容。</div>}</section><section className="rounded-3xl bg-white p-6"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-medium text-[#52655d]">協作通知</p><p className="mt-1 text-sm text-[#7a8b83]">草稿、發布、修改與刪除時寄送 Email。</p></div><button aria-pressed={notifications} onClick={() => setNotifications(!notifications)} className={`relative h-7 w-12 rounded-full transition ${notifications ? "bg-[#c1664b]" : "bg-[#cbd9d1]"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${notifications ? "left-6" : "left-1"}`} /></button></div><p className="mt-4 text-xs text-[#9aa8a0]">{notifications ? "通知已開啟" : "通知已關閉"}</p></section></div>;
}
